# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Maplibre' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Maplibre
pod 'MapboxMaps', '~> 11.0'

end
